-- =============================================================================
-- VISORA — Kullanici/profil olusturma kilavuzu (referans)
-- =============================================================================
-- SaaS modelinde dogrudan kullanici eklemeyin. Su yollari kullanin:
--
-- 1) Platform Owner (sahip) hesabi:
--    Supabase Dashboard -> Authentication -> Add user (e-posta + sifre).
--    Ardindan supabase/seed_platform_owner.sql calistirin.
--
-- 2) Genel Mudur + Sirket olusturma:
--    /visora/companies sayfasi -> "+ Yeni Sirket" formu
--    (veya /api/visora/create-organization endpoint'i).
--
-- 3) Personel ekleme:
--    Genel Mudur paneli -> Personel sayfasindan "Yeni Personel"
--    (/api/org/create-staff). Sirket basina en fazla 3 personel.
--
-- handle_new_user() trigger'i 021_saas_organizations.sql icinde tanimlidir;
-- yeni auth user kaydedildiginde profile satiri otomatik acilir.
-- =============================================================================
