-- =============================================================================
-- Profile manuel insert'i — ARTIK GEREKLI DEGIL
-- =============================================================================
-- Visora SaaS modelinde profile kayitlari otomatik trigger ile olusur.
-- Manuel kullanici ekleme icin /visora/companies (sirket) veya
-- Genel Mudur paneli (personel) arayuzunu kullanin.
-- =============================================================================
